# -*- coding: utf-8 -*-
"""One-shot launch hygiene: robots.txt, sitemap.xml, canonical + OG/twitter tags."""
import html
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://alumoimpact.ca"

EN_PATHS = [
    "/",
    "/about-the-fund/",
    "/apply-now/",
    "/cookies-policy/",
    "/how-to-apply/",
    "/partner-schools/",
    "/past-winners/",
    "/past-winners/2/",
    "/privacy-policy/",
    "/terms-conditions/",
]
ALL_PATHS = EN_PATHS + ["/fr" + p for p in EN_PATHS]

# 1200x630 landscape card (twitter:card=summary_large_image crops ~2:1) —
# generated by _tools/make_og_card.py
OG_IMAGE = BASE + "/assets/img/og-card.png"
OG_IMAGE_WIDTH = 1200
OG_IMAGE_HEIGHT = 630
IMAGE_ALT = {
    "en": "Student smiling with a backpack",
    "fr": "Étudiante souriante avec un sac à dos",
}
SITE_NAME = {
    "en": "Student Impact Fund by Alumo",
    "fr": "Fonds d'impact étudiant par Alumo",
}
LOCALE = {"en": "en_CA", "fr": "fr_CA"}


def page_file(path):
    rel = path.strip("/")
    return os.path.join(ROOT, rel.replace("/", os.sep), "index.html") if rel else os.path.join(ROOT, "index.html")


def esc(s):
    return html.escape(s, quote=True)


# ---------- robots.txt ----------
robots = (
    "User-agent: *\n"
    "Allow: /\n"
    "Disallow: /api/\n"
    "\n"
    "Sitemap: https://alumoimpact.ca/sitemap.xml\n"
)
with io.open(os.path.join(ROOT, "robots.txt"), "w", encoding="utf-8", newline="\n") as f:
    f.write(robots)

# ---------- sitemap.xml ----------
lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
]
for path in ALL_PATHS:
    en_path = path[3:] if path.startswith("/fr") else path
    en_path = en_path or "/"
    fr_path = "/fr" + en_path
    lines.append("  <url>")
    lines.append("    <loc>%s%s</loc>" % (BASE, path))
    lines.append('    <xhtml:link rel="alternate" hreflang="en" href="%s%s"/>' % (BASE, en_path))
    lines.append('    <xhtml:link rel="alternate" hreflang="fr" href="%s%s"/>' % (BASE, fr_path))
    lines.append('    <xhtml:link rel="alternate" hreflang="x-default" href="%s%s"/>' % (BASE, en_path))
    lines.append("  </url>")
lines.append("</urlset>")
with io.open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")

# ---------- head tags ----------
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S)
DESC_RE = re.compile(r'<meta name="description" content="(.*?)"\s*/?>', re.S)
HREFLANG_FR_RE = re.compile(r'^([ \t]*)<link rel="alternate" hreflang="fr"[^>]*>\s*$', re.M)
OG_IMAGE_RE = re.compile(r'^([ \t]*)<meta property="og:image" content="[^"]*">[ \t]*$', re.M)

touched = []
for path in ALL_PATHS:
    fp = page_file(path)
    with io.open(fp, "r", encoding="utf-8") as f:
        src = f.read()
    if 'rel="canonical"' in src or 'property="og:' in src:
        # Already tagged: refresh the social-card image tags in place.
        m = OG_IMAGE_RE.search(src)
        if not m:
            sys.exit("Tagged page without an og:image tag: %s" % fp)
        ind = m.group(1)
        img_lines = ['<meta property="og:image" content="%s">' % OG_IMAGE]
        if 'property="og:image:width"' not in src:
            img_lines.append('<meta property="og:image:width" content="%d">' % OG_IMAGE_WIDTH)
            img_lines.append('<meta property="og:image:height" content="%d">' % OG_IMAGE_HEIGHT)
        new_src = src[: m.start()] + "\n".join(ind + l for l in img_lines) + src[m.end():]
        if new_src != src:
            with io.open(fp, "w", encoding="utf-8", newline="") as f:
                f.write(new_src)
            touched.append(fp)
            print("REFRESHED og:image: %s" % fp)
        else:
            print("SKIP (already current): %s" % fp)
        continue

    lang = "fr" if path.startswith("/fr") else "en"
    title = html.unescape(TITLE_RE.search(src).group(1).strip())
    desc = html.unescape(DESC_RE.search(src).group(1).strip())
    url = BASE + path

    m = HREFLANG_FR_RE.search(src)
    if not m:
        sys.exit("No hreflang=fr link found in %s" % fp)
    indent = m.group(1)

    block_lines = [
        '<link rel="canonical" href="%s">' % url,
        '<meta property="og:type" content="website">',
        '<meta property="og:site_name" content="%s">' % esc(SITE_NAME[lang]),
        '<meta property="og:title" content="%s">' % esc(title),
        '<meta property="og:description" content="%s">' % esc(desc),
        '<meta property="og:url" content="%s">' % url,
        '<meta property="og:locale" content="%s">' % LOCALE[lang],
        '<meta property="og:image" content="%s">' % OG_IMAGE,
        '<meta property="og:image:width" content="%d">' % OG_IMAGE_WIDTH,
        '<meta property="og:image:height" content="%d">' % OG_IMAGE_HEIGHT,
        '<meta property="og:image:alt" content="%s">' % esc(IMAGE_ALT[lang]),
        '<meta name="twitter:card" content="summary_large_image">',
    ]
    block = "\n" + "\n".join(indent + l for l in block_lines)
    new_src = src[: m.end()] + block + src[m.end():]
    with io.open(fp, "w", encoding="utf-8", newline="") as f:
        f.write(new_src)
    touched.append(fp)
    print("TAGGED: %s" % fp)

print("Done. %d pages tagged." % len(touched))
